application: aamasgame
version: 1-6-0-alpha
runtime: python27
threadsafe: false
api_version: 1

handlers:

### STATIC HANDLERS ###
- url: /favicon.ico
  static_files: static/theme/favicon.ico
  upload: static/theme/favicon.ico

- url: /static
  static_dir: static

### DYNAMIC PAGES ###
- url: /tasks/.*
  script: main.py
  login: admin
  
- url: /.*
  script: main.py

builtins:
- deferred: on

libraries:
- name: django
  version: 1.2
